// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace deVoid.UIFramework.Examples {
    
    
    public sealed class ScreenIds {
        
        public const string CameraProjectionWindow = "CameraProjectionWindow";
        
        public const string ConfirmationPopup = "ConfirmationPopup";
        
        public const string HomeWindow = "HomeWindow";
        
        public const string NavigationPanel = "NavigationPanel";
        
        public const string PlayerWindow = "PlayerWindow";
        
        public const string PopupExampleWindow = "PopupExampleWindow";
        
        public const string StartGameWindow = "StartGameWindow";
        
        public const string ThreeDExample = "ThreeDExample";
        
        public const string ToastPanel = "ToastPanel";
    }
}
